dir_path = '/etc/bareos/bareos-dir.d'
sd_path = '/etc/bareos/bareos-sd.d'

%w(
  /device/Example1.conf
  /device/Example2.conf
  /device/Example3.conf
  /device/Example4.conf
).each do |config|
  describe file(sd_path + config) do
    it { should exist }
    its('content') { should match(/Example1 Tape Drive/) } if config == '/device/Example1.conf'
    its('content') { should match(/Example2 Tape Drive/) } if config == '/device/Example2.conf'
    its('content') { should match(/Example3 Tape Drive/) } if config == '/device/Example3.conf'
    its('content') { should match(/Example4 Tape Drive/) } if config == '/device/Example4.conf'
  end
end

# package bareos-storage-tape installed
describe package('bareos-storage-tape') do
  it { should be_installed }
end

# file mtx-changer exists
describe file('/etc/bareos/mtx-changer.conf') do
  it { should exist }
end

%W(
  #{sd_path}/autochanger/autochanger-0.conf.example
  #{sd_path}/device/tapedrive-0.conf.example
  #{dir_path}/storage/Tape.conf.example
).each do |config|
  describe file(config) do
    it { should_not exist }
  end
end

%w(
  /autochanger/autochanger-1-test.conf
  /autochanger/autochanger-2-test.conf
).each do |config|
  describe file(sd_path + config) do
    it { should exist }
    its('content') { should match(/Generated by Chef/) }
    its('content') { should match(/Example1/) } if config == '/autochanger/autochanger-1-test.conf'
    its('content') { should match(/Example2/) } if config == '/autochanger/autochanger-1-test.conf'
    its('content') { should match(/Example3/) } if config == '/autochanger/autochanger-2-test.conf'
    its('content') { should match(/Example4/) } if config == '/autochanger/autochanger-2-test.conf'
    its('content') { should match(/mtx-changer %c %o %S %a %d/) }
  end
end
