---
driver:
  name: vagrant

platforms:
  - name: debian-8
    driver:
      box: bento/debian-8.11
  - name: debian-9
    driver:
      box: bento/debian-9.6
  - name: ubuntu-14
    driver:
      box: bento/ubuntu-14.04
  - name: ubuntu-16
    driver:
      box: bento/ubuntu-16.04
  - name: ubuntu-18
    driver:
      box: bento/ubuntu-18.04
  - name: centos-6
    driver:
      box: bento/centos-6.10
  - name: centos-7
    driver:
      box: bento/centos-7.6

provisioner:
  name: chef_zero
  product_name: chef
  install_strategy: always
  product_version: latest

verifier:
  name: inspec

suites:
  - name: server
    run_list:
      - recipe[bareos-test]
      - recipe[bareos-test::pgsql]
      - recipe[bareos-test::mysql]
      - recipe[bareos-test::python]
      - recipe[bareos-test::director_test]
      - recipe[bareos-test::autochanger_test]
      - recipe[bareos-test::storage_test]
      - recipe[bareos-test::client_test]
      - recipe[bareos-test::console_test]
      - recipe[bareos-test::graphite_poller_test]
