---
driver:
  name: dokken
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken
  always_update_cookbooks: true

platforms:
  - name: ubuntu-16
    driver:
      image: dokken/ubuntu-16.04
      privileged: true
      pid_one_command: /lib/systemd/systemd
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
  - name: centos-7
    driver:
      image: dokken/centos-7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd

verifier:
  name: inspec

suites:
  - name: server
    run_list:
      - recipe[bareos-test]
      - recipe[bareos]
      - recipe[bareos-test::python]
      - recipe[bareos-test::pgsql]
      - recipe[bareos-test::graphite_poller_test]
      - recipe[bareos::storage_daemon_common]
      - recipe[bareos-test::storage_custom_resource_tests]
      - recipe[bareos-test::catalog_test]
      - recipe[bareos::director_common]
      - recipe[bareos-test::director_custom_resource_tests]
