dist: trusty
sudo: required
group: edge
services: docker
addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

stages:
  - lint
  - test

install: echo "skip bundle install"

env:
  - T=server-ubuntu-14
  - T=server-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version
  - rspec --version
  - chef gem install kitchen-dokken

script:
  - chef gem install kitchen-dokken
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test $T -d always

jobs:
  include:
    - stage: lint
      env:
      services:
      sudo:
      language: python
      python: 3.6
      script:
        - pip install pre-commit
        - pre-commit run -a

notifications:
  email:
    recipients:
      - karcaw@gmail.com
      - gitbytes@gmail.com
    on_failure: never
    on_success: always
